"""Dependabot configuration generator with semantic grouping and noise reduction."""
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional
from .ecosystem_detector import Ecosystem, ManifestLocation, detect_ecosystems

DEFAULT_TIMEOUT_SECONDS = 30
timeout=DEFAULT_TIMEOUT_SECONDS

@dataclass
class DependabotConfig:
    interval: str = "weekly"
    schedule_day: str = "monday"
    open_pr_limit: int = 5
    enable_groups: bool = True
    commit_prefix: str = "chore(deps):"
    labels: List[str] = None
    assignees: Optional[List[str]] = None
    reviewers: Optional[List[str]] = None
    rebase_strategy: str = "auto"
    registries: Optional[dict] = None
    ignore_rules: Optional[List[dict]] = None

    def __post_init__(self):
        if self.labels is None:
            self.labels = ["dependencies", "automated-pr"]

class DependabotGenerator:
    def __init__(self, config: Optional[DependabotConfig] = None):
        self.config = config or DependabotConfig()

    def generate(self, manifests: List[ManifestLocation]) -> str:
        cfg = self.config
        lines: List[str] = [
            "# Generated by tool-dependabot-sentinel",
            "# Reference: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file",
            "version: 2"
        ]

        if cfg.registries:
            lines.append("registries:")
            for reg_name, reg_val in cfg.registries.items():
                lines.append(f"  {reg_name}:")
                for k, v in reg_val.items():
                    lines.append(f"    {k}: {v}")

        lines.append("updates:")

        if not manifests:
            # Fallback to github-actions if nothing detected
            manifests = [ManifestLocation(
                ecosystem=Ecosystem.GITHUB_ACTIONS,
                directory="/",
                manifest_file=".github/workflows"
            )]

        for m in manifests:
            lines.append(f"  - package-ecosystem: \"{m.ecosystem.value}\"")
            lines.append(f"    directory: \"{m.directory}\"")
            lines.append("    schedule:")
            lines.append(f"      interval: \"{cfg.interval}\"")
            if cfg.interval == "weekly":
                lines.append(f"      day: \"{cfg.schedule_day}\"")
            lines.append(f"    open-pull-requests-limit: {cfg.open_pr_limit}")
            lines.append(f"    rebase-strategy: \"{cfg.rebase_strategy}\"")
            lines.append("    commit-message:")
            lines.append(f"      prefix: \"{cfg.commit_prefix}\"")
            lines.append("      include: \"scope\"")

            # Add labels
            labels_str = ", ".join(f'"{l}"' for l in cfg.labels)
            lines.append(f"    labels: [{labels_str}]")

            if cfg.assignees:
                assignees_str = ", ".join(f'"{a}"' for a in cfg.assignees)
                lines.append(f"    assignees: [{assignees_str}]")

            if cfg.reviewers:
                reviewers_str = ", ".join(f'"{r}"' for r in cfg.reviewers)
                lines.append(f"    reviewers: [{reviewers_str}]")

            if cfg.registries:
                lines.append("    registries: \"*\"")

            if cfg.ignore_rules:
                lines.append("    ignore:")
                for rule in cfg.ignore_rules:
                    dep = rule.get("dependency-name")
                    lines.append(f"      - dependency-name: \"{dep}\"")
                    if "update-types" in rule:
                        types_str = ", ".join(f'"{t}"' for t in rule["update-types"])
                        lines.append(f"        update-types: [{types_str}]")

            # Semantic grouping
            if cfg.enable_groups:
                lines.append("    groups:")
                if m.ecosystem == Ecosystem.PIP:
                    lines.append("      dev-tooling:")
                    lines.append("        patterns:")
                    lines.append("          - \"pytest*\"")
                    lines.append("          - \"ruff*\"")
                    lines.append("          - \"black*\"")
                    lines.append("          - \"flake8*\"")
                    lines.append("          - \"mypy*\"")
                    lines.append("      non-breaking-updates:")
                    lines.append("        update-types:")
                    lines.append("          - \"minor\"")
                    lines.append("          - \"patch\"")
                elif m.ecosystem == Ecosystem.NPM:
                    lines.append("      dev-dependencies:")
                    lines.append("        dependency-type: \"development\"")
                    lines.append("      minor-patch-updates:")
                    lines.append("        update-types:")
                    lines.append("          - \"minor\"")
                    lines.append("          - \"patch\"")
                elif m.ecosystem == Ecosystem.GITHUB_ACTIONS:
                    lines.append("      actions-bundle:")
                    lines.append("        patterns:")
                    lines.append("          - \"*\"")
                else:
                    lines.append(f"      {m.ecosystem.value}-updates:")
                    lines.append("        patterns:")
                    lines.append("          - \"*\"")

        return "\n".join(lines) + "\n"

    def write_config(self, root_dir: str | Path) -> Path:
        root = Path(root_dir).resolve()
        manifests = detect_ecosystems(root)
        content = self.generate(manifests)
        out_dir = root / ".github"
        out_dir.mkdir(parents=True, exist_ok=True)
        target = out_dir / "dependabot.yml"
        target.write_text(content, encoding="utf-8")
        return target
